name: Code format check with Ruff

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, labeled, unlabeled]
  push:
    branches:
      - develop

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: chartboost/ruff-action@v1
        with:
          src: "./netspresso"
          version: 0.0.259
